# Generated by Django 2.2.1 on 2019-05-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=250)),
                ('_description', models.TextField(blank=True, default='')),
                ('_visibility', models.CharField(max_length=250)),
                ('_web_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_description', models.CharField(max_length=250)),
                ('_default_branch', models.CharField(blank=True, default='', max_length=250)),
                ('_visibility', models.CharField(max_length=250)),
                ('_web_url', models.CharField(max_length=250)),
                ('_avatar_url', models.CharField(blank=True, default='', max_length=250)),
                ('_name', models.CharField(max_length=250)),
                ('_name_with_namespace', models.CharField(max_length=250)),
                ('_created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_username', models.CharField(max_length=250, unique=True)),
                ('_email', models.CharField(max_length=250, unique=True)),
                ('_name', models.CharField(max_length=250)),
                ('_user_state', models.CharField(max_length=250)),
                ('_avatar_url', models.CharField(max_length=250)),
                ('_web_url', models.CharField(max_length=250)),
                ('_is_admin', models.BooleanField()),
                ('_created_at', models.DateTimeField()),
                ('_projects', models.ManyToManyField(to='core_resources.Project')),
            ],
        ),
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=250)),
                ('_description', models.TextField(blank=True, default='')),
                ('_merge_state', models.CharField(max_length=250)),
                ('_web_url', models.CharField(max_length=250)),
                ('_merged_at', models.DateTimeField(null=True)),
                ('_created_at', models.DateTimeField()),
                ('_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_resources.User')),
                ('_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_resources.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=250)),
                ('_issue_state', models.CharField(max_length=250)),
                ('_description', models.TextField(blank=True, default='')),
                ('_web_url', models.CharField(max_length=250)),
                ('_closed_at', models.DateTimeField()),
                ('_created_at', models.DateTimeField()),
                ('_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_resources.User')),
                ('_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_resources.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('_title', models.CharField(max_length=250)),
                ('_committed_date', models.DateTimeField()),
                ('_message', models.TextField(blank=True, default='')),
                ('_created_at', models.DateTimeField()),
                ('_committer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_resources.User')),
                ('_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_resources.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=250)),
                ('_can_push', models.BooleanField()),
                ('_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_resources.Project')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
